<a href="https://colab.research.google.com/github/jihansand/StudyCase-Metode-Numerik/blob/main/Jihan_Sandrina_Halim_2106708160_Kelas_C_Tugas4PrakMetnum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Soal 1

In [ ]:
import numpy as np # untuk membuat array matriks
import random  # untuk mengambil angka random, dari modul numpy
import sympy as sy # untuk simbol
from termcolor import colored  # memberi warna teks yang akan ditampilkan

def GaussElimination(matriks): # mendefinisikan metode eliminasi gauss
    n = np.shape(matriks)[0] # mengambil ukuran baris dari matriks

    for i in range(n):  # mengecek apakah SPL mempunyai solusi
        p = i
        while p < n and matriks[:,i][p] == 0:
            p += 1
        if p == n:
            return 'SPL tidak memiliki solusi unik' # ngecek semua leading one nya ada nol atau ngga, jika semua nol berarti gaada solusi unik
        else:
            if p != i:
                matriks[[p,i]] = matriks[[i,p]] # nuker baris kalo leading one nya ada yg bernilai nol
            for j in range(i+1,n):  # untuk OBE
                m = matriks[j,i]/matriks[i,i]
                matriks[j] = matriks[j]-m*matriks[i] # rumus OBE
    return matriks  # mengembalikan matriks yang sudah diolah

def BackSubstitution(matriks): # mendefinisikan metode back substitution
    n = np.shape(matriks)[0]  # mengambil ukuran baris dari matriks
    solution = np.zeros(n) # ada n jumlah solusi, zeros untuk inisiasi awal matriks
    solution[n-1] = matriks[n-1,n]/matriks[n-1,n-1] # rumus 1
    for i in range(n-2,-1,-1): # rumus 2
        for j in range(i+1,n):
            matriks[i,n] -= matriks[i,j]*solution[j]
        solution[i] = matriks[i,n]/matriks[i,i]
    return solution # mengembalikan nilai solusi yg diperoleh

def PartialPivoting(matriks):
  n = np.shape(matriks)[0] # mengambil ukuran baris dari matriks

  for i in range(n-1):
      below_pivot = abs(matriks[i:,i])  # mencari kolom yang mempunyai nilai absolut maksimum
      pivot_row = np.argmax(below_pivot) # mengambil elemen maksimum

      if matriks[i,pivot_row+i] == 0: # jika baris yang akan di pivot nol, maka tidak ada solusi unik
          return "Tidak ada solusi unik"
      else:
          matriks[[pivot_row+i,i]] = matriks[[i,pivot_row+i]] # menukar baris

      # eliminasi gauss
      for j in range(i+1,n):  # untuk OBE
          m = matriks[j,i]/matriks[i,i]
          matriks[j] = matriks[j] - m*matriks[i]
          print('\n', matrix, '\n')  # menampilkan step-step OBE

  return matriks  # mengembalikan matriks yang telah diolah

def ScaledPartialPivoting(matrix):
  n = np.shape(matrix)[0] # mengambil ukuran baris dari matriks
  s = np.array([max(abs(matrix[i,:n])) for i in range(n)]) # menentukan skalar tiap kolom dibandingkan masing2 baris yang paling besar

  if 0 in s: # SPL tidak memiliki solusi karena ada baris yg hanya berisi 0
    return "tidak ada solusi unik"

  for i in range(n-1):
    below_pivot = abs(matrix[i:,i])/s[i:]
    pivot_row = np.argmax(below_pivot)

    if matrix[i,pivot_row+i] == 0:
      return "Tidak ada solusi unik"
    else:
      matrix[[pivot_row+i,i]] = matrix[[i,pivot_row+i]]
      s[pivot_row+i],s[i] = s[i],s[pivot_row+i]

    #eleminasi gauss
    for j in range(i+1,n): # untuk OBE
      m = matrix[j,i]/matrix[i,i]
      matrix[j] = matrix[j] - m*matrix[i]
      print('\n', matrix, '\n')  # menampilkan step-step OBE

  return matrix # mengembalikan matriks yang telah diolah


def AugmentedMatrix(m,n):  # mendefinisikan augmented matriks
  aug = []  # list kosong untuk diisi matriks yg akan dibentuk

  for i in range(1): # mengulang 1 kali agar terbentuk 1 matriks
    a = [] # list kosong untuk baris pertama matriks
    for i in range(m): # baris
      b = [] # list kosong untuk baris keempat matriks
      for j in range(n): # kolom
        a.append(int(random.randint(-99,100)))  # mengambil angka random sebanyak n kolom lalu dimasukkan ke baris pertama
        b.append(int(random.randint(-99,100)))  # mengambil angka random sebanyak n kolom lalu dimasukkan ke baris keempat
      aug.append(a)  # memasukkan a sbg baris pertama
      aug.append(r22) # memasukkan r22 (5 angka npm awal) sbg baris kedua
      aug.append(r33) # memasukkan r33 (5 angka npm akhir) sbg baris ketiga
      aug.append(b) # memasukkan b sbg baris keempat

      return np.array(aug, dtype = float)  # mengembalikan matriks yang telah diisi

print('Selamat datang di program solusi SPL dengan metode Partial Pivoting dan Scaled Partial Pivoting.')  # ucapan pembuka

while True:  # agar program terus berulang sampai user meminta berhenti
  npm = input('Masukkan NPM anda: ')  # meminta input dr user

  r2 = list(npm[:5])  # mengambil 5 angka awal npm lalu diubah menjadi list
  r3 = list(npm[-5:]) # mengambil 5 angka terakhir npm lalu diubah menjadi list
  r22 = [int(num) for num in r2] # mengubah list menjadi angka
  r33 = [int(num) for num in r3] # mengubah list menjadi angka

  matrix = AugmentedMatrix(4,5)  # mendefinisikan matriks 4x5 yang sudah diisi sblmnya
  matrix2 = np.array(matrix)  # mendefinisikan ulang untuk metode scaled partial pivot agar matriks yang digunakan sama seperti partial pivot
  print('Augmented Matrixnya adalah:\n {}\n'.format(matrix))  # menampilkan matriks yang akan di pivot

  print(colored('=== Partial Pivoting ===', 'blue')) # menampilkan tulisan partial pivot dengan warna biru
  triangular_form = PartialPivoting(matrix)  # inisialisasi pembuatan matriks segitiga dengan metode partial pivot
  print("Triangular matriks dengan Partial Pivoting:\n {}\n".format(triangular_form)) # menampilkan matriks segitiga yg dibentuk
  solution = BackSubstitution(triangular_form) # inisialisasi solusi yang dicari dengan metode back subs
  print('Solusi dari SPL tersebut adalah:\n {}\n'.format(solution)) # menampilkan solusi yang telah dicari

  print(colored('=== Scaled Partial Pivoting ===', 'blue'))  # menampilkan tulisan scaled partial pivot dengan warna biru
  triangular_form2 = ScaledPartialPivoting(matrix2) # inisialisasi pembuatan matriks segitiga dengan metode scaled partial pivot
  print("Triangular matriks dengan Scaled Partial Pivoting:\n {}\n".format(triangular_form))  # menampilkan matriks segitiga yg dibentuk
  solution2 = BackSubstitution(triangular_form2)  # inisialisasi solusi yang dicari dengan metode back subs
  print('Solusi dari SPL tersebut adalah:\n {}\n'.format(solution2)) # menampilkan solusi yang telah dicari

  opsi = sy.Symbol(input('Apakah anda ingin menjalankan program lagi? (Y/N): ')) # membuat pilihan kepada user apakah akan menjalankan ulang program atau ngga
  if opsi == sy.Symbol('y') or opsi == sy.Symbol('Y'):   # jika user memilih menjalankan ulang program
    print('') # spasi
    continue # program akan mengulang
  elif opsi == sy.Symbol('n') or opsi == sy.Symbol('N'):   # jika user memilih tidak menjalankan ulang program
    print('Terima kasih telah menggunakan program ini.') # penutup
    break # program akan berhenti

Selamat datang di program solusi SPL dengan metode Partial Pivoting dan Scaled Partial Pivoting.
Masukkan NPM anda: 2106708160
Augmented Matrixnya adalah:
 [[-15. -89.  93.  66. -15.]
 [  2.   1.   0.   6.   7.]
 [  0.   8.   1.   6.   0.]
 [-36.  78.  81.  61. -64.]]

=== Partial Pivoting ===

 [[-36.          78.          81.          61.         -64.        ]
 [  0.           5.33333333   4.5          9.38888889   3.44444444]
 [  0.           8.           1.           6.           0.        ]
 [-15.         -89.          93.          66.         -15.        ]] 


 [[-36.          78.          81.          61.         -64.        ]
 [  0.           5.33333333   4.5          9.38888889   3.44444444]
 [  0.           8.           1.           6.           0.        ]
 [-15.         -89.          93.          66.         -15.        ]] 


 [[ -36.           78.           81.           61.          -64.        ]
 [   0.            5.33333333    4.5           9.38888889    3.44444444]
 [ 

**PENJELASAN**

Program ini dibuat untuk menyelesaikan SPL matriks 4×5 dengan ketentuan:

*   Elemen-elemen pada baris pertama dan keempat adalah angka random dengan
$$|a_{ij}| < 100, a_{ij} \in Z$$
*   Elemen-elemen pada baris kedua adalah 5 digit pertama NPM
*   Elemen-elemen pada baris ketiga adalah 5 digit terakhir NPM

menggunakan metode **Partial Pivoting** dan **Scaled Partial Pivoting**. Lalu, hasilnya dicari dengan metode **Back Substitution**.

Algoritma program dijelaskan sebagai berikut:
1. Import module-module yang akan digunakan, yaitu `numpy` (untuk membuat matriks), `sympy` (untuk simbol), dan `colored` dari module `termcolor` (untuk mewarnai teks).
2. Definisikan semua rumus metode yang telah diajarkan pada modul 5, yaitu fungsi `GaussElimination`, `BackSubstitution`, `PartialPivoting`, dan `ScaledPartialPivoting`. Lalu, definisikan fungsi untuk membuat matriks berukuran m×n yaitu `AugmentedMatrix` untuk membuat matriks yang telah dijelaskan di atas.
3. Pada fungsi `AugmentedMatrix`, definisikan list kosong yang akan diisi matriks. Lalu, dengan for loop kita membuat matriks. Di dalam loop tersebut ada dua list kosong lagi yang akan diisi angka random untuk baris pertama dan keempat dengan syntax *random.randint*. List diisi dengan syntax *append*. Lalu, akan dihasilkan matriks dengan syntax *np.array* yang sesuai ketentuan soal.
4. Setelah salam pembuka, program masuk ke `while loop` agar dapat terus berulang sampai user meminta berhenti (tidak ingin menjalankan program lagi).
5. Setelah itu, didefinisikan variabel `npm` untuk meminta input NPM user yang akan digunakan nanti.
6. Didefinisikan pula variabel `r2` dan `r3` untuk mengambil 5 digit awal dan 5 digit terakhir NPM lalu diubah menjadi list. Lalu, didefinisikan lagi `r22` dan `r33` yang merubah item-item pada `r2` dan `r3` menjadi integer di dalam list tsb.
7. Lalu, didefinisikan dua matriks yang isinya sama. `matrix` yang memanggil fungsi `AugmentedMatrix` dan `matrix2` yang berisi matriks yang sama dengan `matrix`. Variabel `matrix` akan diolah dengan metode `Partial Pivoting` sementara `matrix2` akan diolah dengan metode `Scaled Partial Pivoting`. Pendefinisian matriks seperti ini dilakukan agar matriks yang digunakan berisi elemen-elemen yang sama, mengingat baris pertama dan keempat adalah angka random. Jika matriks yang akan digunakan hanya didefinisikan sekali, saat menggunakan metode `Scaled Partial Pivoting` matriks akan memanggil angka random yang berbeda dari matriks untuk metode `Partial Pivoting`, sehingga solusi yang dihasilkan nanti akan berbeda.
8. Program akan menampilkan matriks yang akan digunakan.
9. Kemudian, didefinisikan variabel `traingular_form` yang memanggil fungsi `Partial Pivoting` untuk mengolah matriks menjadi matriks segitiga yang menggunakan metode gauss elimination di dalamnya.
10. Lalu, dilanjutkan dengan pendefinisian variabel `solution` yang memanggil metode `BackSubstitution` berisi matriks segitiga yang telah dibentuk pada langkah ke-9 untuk mencari solusi dari matriks tsb.
11. Begitu pula dengan metode `Scaled Partial Pivoting`, langkah yang dilakukan sama seperti langkah 9 dan 10, namun matriks yang digunakan adalah `matrix2`.
12. Program akan menampilkan langkah dan hasil yang didapat dari pengolahan di atas.
13. Selanjutnya, pendefinisian variabel `opsi` untuk menanyakan apakah user akan menjalankan ulang program atau tidak.
14. Jika user ingin menggunakan ulang program (user menginput Y atau y), ada perintah *continue* untuk mengulang program. Jika user tidak ingin menggunakan program (user menginput N atau n), program akan menampilkan salam penutup dan berhenti loop.



# Soal 2

In [ ]:
import numpy as np # untuk membuat array matriks
from termcolor import colored  # memberi warna teks yang akan ditampilkan

def LUFactorization(matrix): # mendefinisikan metode LU Factorization
  n = np.shape(matrix)[0] # mengambil ukuran baris dari matriks
  L = np.identity(n) # mendefinisikan L sebagai matriks identitas nxn

  #operasi baris elementer
  for i in range(n):
    for j in range(i+1, n):
      m = matrix[j,i]/matrix[i,i]
      L[j,i] = m   # memasang elemen L_ji menjadi multiplisitas m = a_ji/a_ii
      matrix[j]= matrix[j]-m*matrix[i]
  return (L, matrix)  # mengembalikan ouput berupa matriks L dan matriks yg telah diolah

print('Selamat datang di program faktorisasi LU matriks.')
matrix = np.array(eval(input('Masukkan matriks yang akan di faktorisasi: ')))  # meminta input matriks yg akan difaktorisasi user
print('=================================== \n')  # pemisah

for i in range(10): # loop untuk mengulang operasi sampai 10 kali
  print('Faktorisasi LU matriks A{}'.format(i)) # menampilkan penjelasan matriks berapa yg sedang difaktorisasi
  L = np.round(LUFactorization(matrix)[0], 0) # mengambil L pada LUFactorization, dibulatkan dengan np.round
  U = np.round(LUFactorization(matrix)[1], 0) # mengambil matrix pada LUFactorization, dibulatkan dengan np.round
  A1 = np.round(L + U)  # mendefinisikan A1 sebagai pertambahan dr L dan U
  print('Matriks L \n{0} \nMatriks U \n{1}'.format(L, U)) # menampilkan matriks L dan U yg telah diolah
  matrix = A1 # mengembalikan A1 sebagai A untuk output terakhir
  print(colored('Matriks A{}'.format(i+1), 'blue')) # menampilkan penjelasan matriks A
  print('{}'.format(A1)) # menampilkan matriks A
  print('=================================== \n') # pemisah

print('Diperoleh matriks A10 adalah \n{}'.format(matrix))  # menampilkan hasil
print('\nTerima kasih telah menggunakan program ini.')  # penutup

Selamat datang di program faktorisasi LU matriks.
Masukkan matriks yang akan di faktorisasi: [[7,3,6],[1,5,2],[6,2,7]]

Faktorisasi LU matriks A0
Matriks L 
[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 1.]] 
Matriks U 
[[7 3 6]
 [0 4 1]
 [0 0 1]]
Matriks A1
[[8. 3. 6.]
 [0. 5. 1.]
 [1. 0. 2.]]

Faktorisasi LU matriks A1
Matriks L 
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]] 
Matriks U 
[[8. 3. 6.]
 [0. 5. 1.]
 [0. 0. 1.]]
Matriks A2
[[9. 3. 6.]
 [0. 6. 1.]
 [0. 0. 2.]]

Faktorisasi LU matriks A2
Matriks L 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
Matriks U 
[[9. 3. 6.]
 [0. 6. 1.]
 [0. 0. 2.]]
Matriks A3
[[10.  3.  6.]
 [ 0.  7.  1.]
 [ 0.  0.  3.]]

Faktorisasi LU matriks A3
Matriks L 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
Matriks U 
[[10.  3.  6.]
 [ 0.  7.  1.]
 [ 0.  0.  3.]]
Matriks A4
[[11.  3.  6.]
 [ 0.  8.  1.]
 [ 0.  0.  4.]]

Faktorisasi LU matriks A4
Matriks L 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
Matriks U 
[[11.  3.  6.]
 [ 0.  8.  1.]
 [ 0.  0.  4.]]
Matriks A5
[[12.  3.  6.]
 [ 0.  

**PENJELASAN**

Program ini dibuat untuk menemukan angka-angka untuk membuka peti dengan metode `LU Factorization`. Metode `LU Factorization` membuat matriks segitiga bawah (L) dan matriks segitiga atas (U) dari matriks yang akan dimasukkan.

Algoritma program dijelaskan sebagai berikut:
1. Import modul yang akan digunakan, yaitu `numpy` (untuk membuat array matriks) dan `colored` dari module `termcolor` (untuk mewarnai teks).
2. Definisikan fungsi `LUFactorization` yang telah diajarkan pada modul 5.
3. Lalu, ada salam pembuka.
4. Setelah itu, definisikan variabel `matrix` untuk meminta input isi matriks dari user. Program akan membuat matriks dengan syntax *np.array*.
5. Program masuk ke for loop untuk mengulang proses faktorisasi sebanyak 10 kali seperti yang diminta soal.
6. Pada loop, definisikan variabel `L` untuk mengambil segitiga bawah dan `U` untuk mengambil segitiga atas dari matriks yang dimasukkan yang telah diolah oleh fungsi `LUFactorization`. Lalu, elemen-elemen pada hasilnya dibulatkan dengan syntax *np.round* untuk menghindari angka yang terlalu rumit.
7. Selanjutnya, didefinisikan variabel `A1` yang merupakah pertambahan `L` dan `U` sesuai instruksi pada soal. Lalu, didefinisikan pula variabel `A` untuk ditampilkan sebagai hasil akhir nanti (A10).
8. Semua matriks yang diolah ditampilkan, sehingga menghasilkan matriks **A10** yang merupakan hasil akhir faktorisasi.
