<a href="https://colab.research.google.com/github/jihansand/StudyCase-Metode-Numerik/blob/main/Jihan_Sandrina_Halim_2106708160_Kelas_C_Tugas5PrakMetnum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Penjelasan program

Program ini dibuat untuk mencari solusi SPL dengan metode iterasi Jacobi dan Gauss-Seidel. Algoritmanya di jelaskan sebagai berikut:

1.   Import module-module yang akan digunakan, yaitu `numpy` (untuk membuat array matriks), `sympy` (untuk simbol), `tabulate` (untuk membuat tabel), dan `colored` dari module `termcolor` (untuk mewarnai teks).
2. Mendefinisikan metode Jacobi dan Gauss-Seidel seperti yang sudah dijelaskan pada modul 6. Namun, di dalamnya terdapat tambahan syntax untuk membuat tabel yang berisi iterasi-iterasinya.
3. Pembuatan tabel iterasinya dimulai dengan membuat list kosong sebagai variabel `iterasi` dan inisiasi iterasi dimulai dari satu dengan variabel `j_iterasi`.
4. Lalu, setelah masuk ke rumus metodenya, digunakan syntax *append()* untuk memasukkan list ke list kosong tadi.
5. Setelahnya, mendefinisikan variabel `isi` yang menggunakan syntax *insert()* untuk menyatukan solusi-solusi x dan berdasarkan iterasinya, serta agar memisahkannya menjadi beberapa kolom sesuai x yang dicari (x1, x2, x3, dst). Terakhir, digunakan lagi syntax *append()* untuk memasukkan semual hasil ke dalam list untuk menjadi tabel.
6. Selanjutnya, mendefinisikan variabel-variabel yang dibutuhkan dan memerlukan input dari user, yaitu `aug_matrix` (augmented matriks dari SPL yang akan dicari solusinya), `initial_solution` (tebakan awal solusi SPL), dan `tolerance` (batas toleransi).
7. Jika input sudah sesuai, program akan mencari solusinya dengan memanggil fungsi dari metode Jacobi dan Gauss-Seidel.
8. Karena tabel didefinisikan di dalem fungsi, setelah memanggil fungsi tsb maka hasil iterasi dan solusi SPL tersebut akan langsung ditampilkan.




# **Soal 1**

In [ ]:
import numpy as np # untuk membuat array matriks
from tabulate import tabulate  # untuk membuat tabel
import sympy as sy # untuk simbol
from termcolor import colored  # memberi warna teks yang akan ditampilkan

def GaussSeidel(matrix, initial, tol):   # mendefinisikan metode Gauss-Seidel
  n = np.shape(matrix)[0]   # mengambil ukuran matriks/banyak variabelnya
  x0 = initial              # inisialisasi tebakan awal sebagai x0
  x = x0.copy()             # inisialisasi x. Menggunakan copy() karena jika x0 berubah, x tidak akan berubah

  iterasi = []                             # list kosong yang akan diisi oleh iterasi
  j_iterasi =  1                           # inisialisasi iterasi ke-sekian untuk dimasukkan pada tabel (iterasi dimulai dr satu)

  for i in range(n):
    b = matrix[i,n]      # konstanta pada SPL
    for j in range(n):   # metode Gauss-Seidel
      if j!=i:
        if j<i:
          b -= matrix[i,j]*x[j]
        else:
          b -= matrix[i,j]*x0[j]
    x[i] = b/matrix[i,i]                    # hasil aproksimasi Gauss-Seidel
  isi = np.insert(x, 0, j_iterasi) # inisialisasi solusi-solusi x dari hasil iterasi untuk dimasukkan ke tabel
  iterasi.append(isi)              # menambahkan solusi-solusi x ke tabel

  while np.linalg.norm(x-x0, np.inf)>=tol:  # mengecek batas toleransi dengan error mutlak
    x0 = x                                  # inisialisasi x0 sebagai x(k-1)
    x = x0.copy()                           # inisialisasi x sebagai x(k) tapi awalnya sama dengan x0

    for i in range(n):   # metode Gauss-Seidel
      b = matrix[i,n]
      for j in range(n):
        if j!=i:
          if j<i:
            b -= matrix[i,j]*x[j]
          else:
            b -= matrix[i,j]*x0[j]
      x[i] = b/matrix[i,i]

    j_iterasi += 1                   # iterasi bergerak dengan bertambah 1 terus
    isi = np.insert(x, 0, j_iterasi) # inisialisasi solusi-solusi x dari hasil iterasi untuk dimasukkan ke tabel
    iterasi.append(isi)              # menambahkan solusi-solusi x ke tabel

  print(colored('Tabel iterasi Gauss-Seidel:','blue'))  # menampilkan tulisan untuk tabel iterasi Gauss-Seidel
  print(tabulate(iterasi, headers =["Iterasi","X1",'X2','X3'], tablefmt = "fancy_grid")) # menampilkan seluruh hasil x sesuai iterasinya dalam bentuk tabel

  return x        # nilai yang di-return fungsi ini adalah x(k)

def Jacobi(matrix, initial, tol):   # mendefinisikan metode Jacobi
  n = np.shape(matrix)[0]  # mengambil ukuran matriks/banyak variabelnya
  x0 = initial             # inisialisasi tebakan awal sebagai x0
  x = x0.copy()            # inisialisasi x. Menggunakan copy() karena jika x0 berubah, x tidak akan berubah

  iterasi = []                             # list kosong yang akan diisi oleh iterasi
  j_iterasi =  1                           # inisialisasi iterasi ke-sekian untuk dimasukkan pada tabel (iterasi dimulai dr satu)

  for i in range(n):
    b = matrix[i,n]      # konstanta pada SPL
    for j in range(n):   # metode Jacobi
      if j!=i:
        b -= matrix[i,j]*x0[j]
    x[i] = b/matrix[i,i]           # hasil aproksimasi Jacobi
  isi = np.insert(x, 0, j_iterasi) # inisialisasi solusi-solusi x dari hasil iterasi untuk dimasukkan ke tabel
  iterasi.append(isi)              # menambahkan solusi-solusi x ke tabel

  while np.linalg.norm(x-x0, np.inf)>=tol:   # mengecek batas toleransi dengan error mutlak
    x0 = x                                   # inisialisasi x0 sebagai x(k-1)
    x = x0.copy()                            # inisialisasi x sebagai x(k) tapi awalnya sama dengan x0

    for i in range(n):     # metode Jacobi
      b = matrix[i,n]
      for j in range(n):
        if j!=i:
          b -= matrix[i,j]*x0[j]
      x[i] = b/matrix[i,i]

    j_iterasi += 1                   # iterasi bergerak dengan bertambah 1 terus
    isi = np.insert(x, 0, j_iterasi) # inisialisasi solusi-solusi x dari hasil iterasi untuk dimasukkan ke tabel
    iterasi.append(isi)              # menambahkan solusi-solusi x ke tabel

  print(colored('Tabel iterasi Jacobi:','blue'))  # menampilkan tulisan untuk tabel iterasi Jacobi
  print(tabulate(iterasi, headers =["Iterasi","X1",'X2','X3'], tablefmt = "fancy_grid")) # menampilkan seluruh hasil x sesuai iterasinya dalam bentuk tabel

  return x   # nilai x yang direturn fungsi ini adalah x(k)


print('Selamat datang di program iterasi solusi SPL dengan metode Jacobi dan Gauss-Seidel.')
aug_matrix = np.array(eval(input('Masukkan augmented matrix dari SPL yang akan diselesaikan: ')))  # meminta input matriks dari user lalu dibentuk menjadi array
initial_solution = np.array(eval(input('Masukkan tebakan awal solusi: ')), dtype = float)  # meminta input inisiasi awal solusi dengan tipe float
tolerance = eval(input('Masukkan toleransi: '))  # meminta input batas toleransi yang diinginkan
print('Augmented matrixnya adalah:', '\n', aug_matrix, '\n')  # menampilkan array matriks yang terbentuk
print('Aproksimasi solusi SPL tersebut dengan metode Jacobi adalah: {}'.format(Jacobi(aug_matrix, initial_solution, tolerance)),'\n')        # menampilkan solusi x dari metode Jacobi dengan memanggil fungsi Jacobi
print('Aproksimasi solusi SPL tersebut dengan metode Gauss-Seidel adalah: {}'.format(GaussSeidel(aug_matrix, initial_solution, tolerance)), '\n')  # menampilkan solusi x dari metode Gauss-Seidel dengan memanggil fungsi Gauss-Seidel
print('Terima kasih telah menggunakan program ini.') # penutup

Selamat datang di program iterasi solusi SPL dengan metode Jacobi dan Gauss-Seidel.
Masukkan augmented matrix dari SPL yang akan diselesaikan: [[3,-1,1,4],[1,2,1,8],[1,1,-2,-3]]
Masukkan tebakan awal solusi: [0,0,0]
Masukkan toleransi: 10**-3
Augmented matrixnya adalah: 
 [[ 3 -1  1  4]
 [ 1  2  1  8]
 [ 1  1 -2 -3]] 

Tabel iterasi Jacobi:
╒═══════════╤══════════╤══════════╤═════════╕
│   Iterasi │       X1 │       X2 │      X3 │
╞═══════════╪══════════╪══════════╪═════════╡
│         1 │ 1.33333  │ 4        │ 1.5     │
├───────────┼──────────┼──────────┼─────────┤
│         2 │ 2.16667  │ 2.58333  │ 4.16667 │
├───────────┼──────────┼──────────┼─────────┤
│         3 │ 0.805556 │ 0.833333 │ 3.875   │
├───────────┼──────────┼──────────┼─────────┤
│         4 │ 0.319444 │ 1.65972  │ 2.31944 │
├───────────┼──────────┼──────────┼─────────┤
│         5 │ 1.11343  │ 2.68056  │ 2.48958 │
├───────────┼──────────┼──────────┼─────────┤
│         6 │ 1.39699  │ 2.1985   │ 3.39699 │
├───────────┼

In [ ]:
# nomor 1d
import numpy as np # untuk membuat array matriks
from tabulate import tabulate  # untuk membuat tabel
import sympy as sy # untuk simbol
from termcolor import colored  # memberi warna teks yang akan ditampilkan

def GaussSeidel(matrix, initial, tol):   # mendefinisikan metode Gauss-Seidel
  n = np.shape(matrix)[0]   # mengambil ukuran matriks/banyak variabelnya
  x0 = initial              # inisialisasi tebakan awal sebagai x0
  x = x0.copy()             # inisialisasi x. Menggunakan copy() karena jika x0 berubah, x tidak akan berubah

  iterasi = []                          # list kosong yang akan diisi oleh iterasi
  j_iterasi =  1                        # inisialisasi iterasi ke-sekian untuk dimasukkan pada tabel (iterasi dimulai dr satu)

  for i in range(n):
    b = matrix[i,n]      # konstanta pada SPL
    for j in range(n):   # metode Gauss-Seidel
      if j!=i:
        if j<i:
          b -= matrix[i,j]*x[j]
        else:
          b -= matrix[i,j]*x0[j]
    x[i] = b/matrix[i,i]                    # hasil aproksimasi Gauss-Seidel
  isi = np.insert(x, 0, j_iterasi)          # inisialisasi solusi-solusi x dari hasil iterasi untuk dimasukkan ke tabel
  iterasi.append(isi)                       # menambahkan solusi-solusi x ke tabel

  while np.linalg.norm(x-x0, np.inf)>=tol:  # mengecek batas toleransi dengan error mutlak
    x0 = x                                  # inisialisasi x0 sebagai x(k-1)
    x = x0.copy()                           # inisialisasi x sebagai x(k) tapi awalnya sama dengan x0

    for i in range(n):   # metode Gauss-Seidel
      b = matrix[i,n]
      for j in range(n):
        if j!=i:
          if j<i:
            b -= matrix[i,j]*x[j]
          else:
            b -= matrix[i,j]*x0[j]
      x[i] = b/matrix[i,i]

    j_iterasi += 1                   # iterasi bergerak dengan bertambah 1 terus
    isi = np.insert(x, 0, j_iterasi) # inisialisasi solusi-solusi x dari hasil iterasi untuk dimasukkan ke tabel
    iterasi.append(isi)              # menambahkan solusi-solusi x ke tabel

  print(colored('Tabel iterasi Gauss-Seidel:','blue'))  # menampilkan tulisan untuk tabel iterasi Gauss-Seidel
  print(tabulate(iterasi, headers =["Iterasi","X1",'X2','X3'], tablefmt = "fancy_grid")) # menampilkan seluruh hasil x sesuai iterasinya dalam bentuk tabel

  return x        # nilai yang di-return fungsi ini adalah x(k)

def Jacobi(matrix, initial, tol):   # mendefinisikan metode Jacobi
  n = np.shape(matrix)[0]  # mengambil ukuran matriks/banyak variabelnya
  x0 = initial             # inisialisasi tebakan awal sebagai x0
  x = x0.copy()            # inisialisasi x. Menggunakan copy() karena jika x0 berubah, x tidak akan berubah

  iterasi = []                             # list kosong yang akan diisi oleh iterasi
  j_iterasi =  1                           # inisialisasi iterasi ke-sekian untuk dimasukkan pada tabel (iterasi dimulai dr satu)

  for i in range(n):
    b = matrix[i,n]      # konstanta pada SPL
    for j in range(n):   # metode Jacobi
      if j!=i:
        b -= matrix[i,j]*x0[j]
    x[i] = b/matrix[i,i]           # hasil aproksimasi Jacobi
  isi = np.insert(x, 0, j_iterasi) # inisialisasi solusi-solusi x dari hasil iterasi untuk dimasukkan ke tabel
  iterasi.append(isi)              # menambahkan solusi-solusi x ke tabel

  while np.linalg.norm(x-x0, np.inf)>=tol:   # mengecek batas toleransi dengan error mutlak
    x0 = x                                   # inisialisasi x0 sebagai x(k-1)
    x = x0.copy()                            # inisialisasi x sebagai x(k) tapi awalnya sama dengan x0

    for i in range(n):     # metode Jacobi
      b = matrix[i,n]
      for j in range(n):
        if j!=i:
          b -= matrix[i,j]*x0[j]
      x[i] = b/matrix[i,i]

    j_iterasi += 1                   # iterasi bergerak dengan bertambah 1 terus
    isi = np.insert(x, 0, j_iterasi) # inisialisasi solusi-solusi x dari hasil iterasi untuk dimasukkan ke tabel
    iterasi.append(isi)              # menambahkan solusi-solusi x ke tabel

  print(colored('Tabel iterasi Jacobi:','blue'))  # menampilkan tulisan untuk tabel iterasi Jacobi
  print(tabulate(iterasi, headers =["Iterasi","X1",'X2','X3'], tablefmt = "fancy_grid")) # menampilkan seluruh hasil x sesuai iterasinya dalam bentuk tabel

  return x   # nilai x yang direturn fungsi ini adalah x(k)


print('Selamat datang di program iterasi solusi SPL dengan metode Jacobi dan Gauss-Seidel.')
aug_matrix = np.array(eval(input('Masukkan augmented matrix dari SPL yang akan diselesaikan: ')))  # meminta input matriks dari user lalu dibentuk menjadi array
initial_solution = np.array(eval(input('Masukkan tebakan awal solusi: ')), dtype = float)  # meminta input inisiasi awal solusi dengan tipe float
tolerance = eval(input('Masukkan toleransi: '))  # meminta input batas toleransi yang diinginkan
print('Augmented matrixnya adalah:', '\n', aug_matrix, '\n')  # menampilkan array matriks yang terbentuk
print('Aproksimasi solusi SPL tersebut dengan metode Jacobi adalah: {}'.format(Jacobi(aug_matrix, initial_solution, tolerance)),'\n')        # menampilkan solusi x dari metode Jacobi dengan memanggil fungsi Jacobi
print('Aproksimasi solusi SPL tersebut dengan metode Gauss-Seidel adalah: {}'.format(GaussSeidel(aug_matrix, initial_solution, tolerance)), '\n')  # menampilkan solusi x dari metode Gauss-Seidel dengan memanggil fungsi Gauss-Seidel
print('Terima kasih telah menggunakan program ini.') # penutup

Selamat datang di program iterasi solusi SPL dengan metode Jacobi dan Gauss-Seidel.
Masukkan augmented matrix dari SPL yang akan diselesaikan: [[2,-1,1,-1],[2,2,2,4],[-1,-1,2,-5]]
Masukkan tebakan awal solusi: [1,1,1]
Masukkan toleransi: 10**-5
Augmented matrixnya adalah: 
 [[ 2 -1  1 -1]
 [ 2  2  2  4]
 [-1 -1  2 -5]] 



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:75: RuntimeWarning: overflow encountered in double_scalars
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:75: RuntimeWarning: invalid value encountered in double_scalars
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:67: RuntimeWarning: invalid value encountered in subtract


Streaming output truncated to the last 5000 lines.
├───────────┼────────────────────┼────────────────────┼────────────────────┤
│      3883 │       1.89857e+188 │       2.53143e+188 │       6.32857e+187 │
├───────────┼────────────────────┼────────────────────┼────────────────────┤
│      3884 │       9.49285e+187 │      -2.53143e+188 │       2.215e+188   │
├───────────┼────────────────────┼────────────────────┼────────────────────┤
│      3885 │      -2.37321e+188 │      -3.16428e+188 │      -7.91071e+187 │
├───────────┼────────────────────┼────────────────────┼────────────────────┤
│      3886 │      -1.18661e+188 │       3.16428e+188 │      -2.76875e+188 │
├───────────┼────────────────────┼────────────────────┼────────────────────┤
│      3887 │       2.96651e+188 │       3.95535e+188 │       9.88838e+187 │
├───────────┼────────────────────┼────────────────────┼────────────────────┤
│      3888 │       1.48326e+188 │      -3.95535e+188 │       3.46093e+188 │
├───────────┼────────────

a. Cell di atas adalah aproksimasi solusi SPL dengan metode Jacobi dan Gauss-Seidel.

b. Pada metode Gauss-Seidel hanya dibutuhkan 24 iterasi sampai mencapai batas toleransi. Sedangkan pada metode Jacobi dibutuhkan lebih dari 5000 iterasi. Bahkan metode Jacobi tidak berhasil mendapat solusi dari SPL tersebut karena SPL tidak konvergen.

c. Iya, karena pada metode Gauss-Seidel, solusi x yang didapat tiap iterasinya langsung digunakan (di update) untuk menghitung iterasi berikutnya. Hal ini mempercepat proses iterasi menuju solusi SPL yang diharapkan.

d. Iya, tetapi hasil aproksimasinya hanya berbeda sangat kecil. Iterasi yang dijalankan juga berbeda 1. Hal ini mungkin terjadi karena aproksimasi awal yang berbeda tersebut.


# Soal 2

In [ ]:
import numpy as np # untuk membuat array matriks
from tabulate import tabulate  # untuk membuat tabel
import sympy as sy # untuk simbol
from termcolor import colored  # memberi warna teks yang akan ditampilkan

def GaussSeidel(matrix, initial, tol):   # mendefinisikan metode Gauss-Seidel
  n = np.shape(matrix)[0]   # mengambil ukuran matriks/banyak variabelnya
  x0 = initial              # inisialisasi tebakan awal sebagai x0
  x = x0.copy()             # inisialisasi x. Menggunakan copy() karena jika x0 berubah, x tidak akan berubah

  iterasi = []                          # list kosong yang akan diisi oleh iterasi
  j_iterasi =  1                        # inisialisasi iterasi ke-sekian untuk dimasukkan pada tabel (iterasi dimulai dr satu)

  for i in range(n):
    b = matrix[i,n]      # konstanta pada SPL
    for j in range(n):   # metode Gauss-Seidel
      if j!=i:
        if j<i:
          b -= matrix[i,j]*x[j]
        else:
          b -= matrix[i,j]*x0[j]
    x[i] = b/matrix[i,i]                    # hasil aproksimasi Gauss-Seidel
  isi = np.insert(x, 0, j_iterasi)          # inisialisasi solusi-solusi x dari hasil iterasi untuk dimasukkan ke tabel
  iterasi.append(isi)                       # menambahkan solusi-solusi x ke tabel

  while np.linalg.norm(x-x0, np.inf)>=tol:  # mengecek batas toleransi dengan error mutlak
    x0 = x                                  # inisialisasi x0 sebagai x(k-1)
    x = x0.copy()                           # inisialisasi x sebagai x(k) tapi awalnya sama dengan x0

    for i in range(n):   # metode Gauss-Seidel
      b = matrix[i,n]
      for j in range(n):
        if j!=i:
          if j<i:
            b -= matrix[i,j]*x[j]
          else:
            b -= matrix[i,j]*x0[j]
      x[i] = b/matrix[i,i]

    j_iterasi += 1                   # iterasi bergerak dengan bertambah 1 terus
    isi = np.insert(x, 0, j_iterasi) # inisialisasi solusi-solusi x dari hasil iterasi untuk dimasukkan ke tabel
    iterasi.append(isi)              # menambahkan solusi-solusi x ke tabel

  print(colored('Tabel iterasi Gauss-Seidel:','blue'))  # menampilkan tulisan untuk tabel iterasi Gauss-Seidel
  print(tabulate(iterasi, headers =["Iterasi","X1",'X2','X3'], tablefmt = "fancy_grid")) # menampilkan seluruh hasil x sesuai iterasinya dalam bentuk tabel

  return x        # nilai yang di-return fungsi ini adalah x(k)

def Jacobi(matrix, initial, tol):   # mendefinisikan metode Jacobi
  n = np.shape(matrix)[0]  # mengambil ukuran matriks/banyak variabelnya
  x0 = initial             # inisialisasi tebakan awal sebagai x0
  x = x0.copy()            # inisialisasi x. Menggunakan copy() karena jika x0 berubah, x tidak akan berubah

  iterasi = []                             # list kosong yang akan diisi oleh iterasi
  j_iterasi =  1                           # inisialisasi iterasi ke-sekian untuk dimasukkan pada tabel (iterasi dimulai dr satu)

  for i in range(n):
    b = matrix[i,n]      # konstanta pada SPL
    for j in range(n):   # metode Jacobi
      if j!=i:
        b -= matrix[i,j]*x0[j]
    x[i] = b/matrix[i,i]           # hasil aproksimasi Jacobi
  isi = np.insert(x, 0, j_iterasi) # inisialisasi solusi-solusi x dari hasil iterasi untuk dimasukkan ke tabel
  iterasi.append(isi)              # menambahkan solusi-solusi x ke tabel

  while np.linalg.norm(x-x0, np.inf)>=tol:   # mengecek batas toleransi dengan error mutlak
    x0 = x                                   # inisialisasi x0 sebagai x(k-1)
    x = x0.copy()                            # inisialisasi x sebagai x(k) tapi awalnya sama dengan x0

    for i in range(n):     # metode Jacobi
      b = matrix[i,n]
      for j in range(n):
        if j!=i:
          b -= matrix[i,j]*x0[j]
      x[i] = b/matrix[i,i]

    j_iterasi += 1                   # iterasi bergerak dengan bertambah 1 terus
    isi = np.insert(x, 0, j_iterasi) # inisialisasi solusi-solusi x dari hasil iterasi untuk dimasukkan ke tabel
    iterasi.append(isi)              # menambahkan solusi-solusi x ke tabel

  print(colored('Tabel iterasi Jacobi:','blue'))  # menampilkan tulisan untuk tabel iterasi Jacobi
  print(tabulate(iterasi, headers =["Iterasi","X1",'X2','X3'], tablefmt = "fancy_grid")) # menampilkan seluruh hasil x sesuai iterasinya dalam bentuk tabel

  return x   # nilai x yang direturn fungsi ini adalah x(k)


print('Selamat datang di program iterasi solusi SPL dengan metode Jacobi dan Gauss-Seidel.')
aug_matrix = np.array(eval(input('Masukkan augmented matrix dari SPL yang akan diselesaikan: ')))  # meminta input matriks dari user lalu dibentuk menjadi array
initial_solution = np.array(eval(input('Masukkan tebakan awal solusi: ')), dtype = float)  # meminta input inisiasi awal solusi dengan tipe float
tolerance = eval(input('Masukkan toleransi: '))  # meminta input batas toleransi yang diinginkan
print('Augmented matrixnya adalah:', '\n', aug_matrix, '\n')  # menampilkan array matriks yang terbentuk
print('Aproksimasi solusi SPL tersebut dengan metode Jacobi adalah: {}'.format(Jacobi(aug_matrix, initial_solution, tolerance)),'\n')        # menampilkan solusi x dari metode Jacobi dengan memanggil fungsi Jacobi
print('Terima kasih telah menggunakan program ini.') # penutup

Selamat datang di program iterasi solusi SPL dengan metode Jacobi dan Gauss-Seidel.
Masukkan augmented matrix dari SPL yang akan diselesaikan: [[1,4,1,2,8],[1,4,1,1,7],[1,2,3,2,8],[1,1,7,4,14]]
Masukkan tebakan awal solusi: [1,1,1,1]
Masukkan toleransi: 10**-4
Augmented matrixnya adalah: 
 [[ 1  4  1  2  8]
 [ 1  4  1  1  7]
 [ 1  2  3  2  8]
 [ 1  1  7  4 14]] 



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:74: RuntimeWarning: overflow encountered in double_scalars
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:74: RuntimeWarning: overflow encountered in multiply


KeyboardInterrupt: ignored

In [ ]:
import numpy as np # untuk membuat array matriks
from tabulate import tabulate  # untuk membuat tabel
import sympy as sy # untuk simbol
from termcolor import colored  # memberi warna teks yang akan ditampilkan

def GaussSeidel(matrix, initial, tol):   # mendefinisikan metode Gauss-Seidel
  n = np.shape(matrix)[0]   # mengambil ukuran matriks/banyak variabelnya
  x0 = initial              # inisialisasi tebakan awal sebagai x0
  x = x0.copy()             # inisialisasi x. Menggunakan copy() karena jika x0 berubah, x tidak akan berubah

  iterasi = []                          # list kosong yang akan diisi oleh iterasi
  j_iterasi =  1                        # inisialisasi iterasi ke-sekian untuk dimasukkan pada tabel (iterasi dimulai dr satu)

  for i in range(n):
    b = matrix[i,n]      # konstanta pada SPL
    for j in range(n):   # metode Gauss-Seidel
      if j!=i:
        if j<i:
          b -= matrix[i,j]*x[j]
        else:
          b -= matrix[i,j]*x0[j]
    x[i] = b/matrix[i,i]                    # hasil aproksimasi Gauss-Seidel
  isi = np.insert(x, 0, j_iterasi)          # inisialisasi solusi-solusi x dari hasil iterasi untuk dimasukkan ke tabel
  iterasi.append(isi)                       # menambahkan solusi-solusi x ke tabel

  while np.linalg.norm(x-x0, np.inf)>=tol:  # mengecek batas toleransi dengan error mutlak
    x0 = x                                  # inisialisasi x0 sebagai x(k-1)
    x = x0.copy()                           # inisialisasi x sebagai x(k) tapi awalnya sama dengan x0

    for i in range(n):   # metode Gauss-Seidel
      b = matrix[i,n]
      for j in range(n):
        if j!=i:
          if j<i:
            b -= matrix[i,j]*x[j]
          else:
            b -= matrix[i,j]*x0[j]
      x[i] = b/matrix[i,i]

    j_iterasi += 1                   # iterasi bergerak dengan bertambah 1 terus
    isi = np.insert(x, 0, j_iterasi) # inisialisasi solusi-solusi x dari hasil iterasi untuk dimasukkan ke tabel
    iterasi.append(isi)              # menambahkan solusi-solusi x ke tabel

  print(colored('Tabel iterasi Gauss-Seidel:','blue'))  # menampilkan tulisan untuk tabel iterasi Gauss-Seidel
  print(tabulate(iterasi, headers =["Iterasi","X1",'X2','X3'], tablefmt = "fancy_grid")) # menampilkan seluruh hasil x sesuai iterasinya dalam bentuk tabel

  return x        # nilai yang di-return fungsi ini adalah x(k)

def Jacobi(matrix, initial, tol):   # mendefinisikan metode Jacobi
  n = np.shape(matrix)[0]  # mengambil ukuran matriks/banyak variabelnya
  x0 = initial             # inisialisasi tebakan awal sebagai x0
  x = x0.copy()            # inisialisasi x. Menggunakan copy() karena jika x0 berubah, x tidak akan berubah

  iterasi = []                             # list kosong yang akan diisi oleh iterasi
  j_iterasi =  1                           # inisialisasi iterasi ke-sekian untuk dimasukkan pada tabel (iterasi dimulai dr satu)

  for i in range(n):
    b = matrix[i,n]      # konstanta pada SPL
    for j in range(n):   # metode Jacobi
      if j!=i:
        b -= matrix[i,j]*x0[j]
    x[i] = b/matrix[i,i]           # hasil aproksimasi Jacobi
  isi = np.insert(x, 0, j_iterasi) # inisialisasi solusi-solusi x dari hasil iterasi untuk dimasukkan ke tabel
  iterasi.append(isi)              # menambahkan solusi-solusi x ke tabel

  while np.linalg.norm(x-x0, np.inf)>=tol:   # mengecek batas toleransi dengan error mutlak
    x0 = x                                   # inisialisasi x0 sebagai x(k-1)
    x = x0.copy()                            # inisialisasi x sebagai x(k) tapi awalnya sama dengan x0

    for i in range(n):     # metode Jacobi
      b = matrix[i,n]
      for j in range(n):
        if j!=i:
          b -= matrix[i,j]*x0[j]
      x[i] = b/matrix[i,i]

    j_iterasi += 1                   # iterasi bergerak dengan bertambah 1 terus
    isi = np.insert(x, 0, j_iterasi) # inisialisasi solusi-solusi x dari hasil iterasi untuk dimasukkan ke tabel
    iterasi.append(isi)              # menambahkan solusi-solusi x ke tabel

  print(colored('Tabel iterasi Jacobi:','blue'))  # menampilkan tulisan untuk tabel iterasi Jacobi
  print(tabulate(iterasi, headers =["Iterasi","X1",'X2','X3'], tablefmt = "fancy_grid")) # menampilkan seluruh hasil x sesuai iterasinya dalam bentuk tabel

  return x   # nilai x yang direturn fungsi ini adalah x(k)


print('Selamat datang di program iterasi solusi SPL dengan metode Jacobi dan Gauss-Seidel.')
aug_matrix = np.array(eval(input('Masukkan augmented matrix dari SPL yang akan diselesaikan: ')))  # meminta input matriks dari user lalu dibentuk menjadi array
initial_solution = np.array(eval(input('Masukkan tebakan awal solusi: ')), dtype = float)  # meminta input inisiasi awal solusi dengan tipe float
tolerance = eval(input('Masukkan toleransi: '))  # meminta input batas toleransi yang diinginkan
print('Augmented matrixnya adalah:', '\n', aug_matrix, '\n')  # menampilkan array matriks yang terbentuk
print('Aproksimasi solusi SPL tersebut dengan metode Gauss-Seidel adalah: {}'.format(GaussSeidel(aug_matrix, initial_solution, tolerance)), '\n')  # menampilkan solusi x dari metode Gauss-Seidel dengan memanggil fungsi Gauss-Seidel
print('Terima kasih telah menggunakan program ini.') # penutup

Selamat datang di program iterasi solusi SPL dengan metode Jacobi dan Gauss-Seidel.
Masukkan augmented matrix dari SPL yang akan diselesaikan: [[1,4,1,2,8],[1,4,1,1,7],[1,2,3,2,8],[1,1,7,4,14]]
Masukkan tebakan awal solusi: [1,1,1,1]
Masukkan toleransi: 10**-4
Augmented matrixnya adalah: 
 [[ 1  4  1  2  8]
 [ 1  4  1  1  7]
 [ 1  2  3  2  8]
 [ 1  1  7  4 14]] 



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:35: RuntimeWarning: overflow encountered in multiply
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:37: RuntimeWarning: invalid value encountered in double_scalars


Tabel iterasi Gauss-Seidel:


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



SPL pada soal nomor 2 bersifat divergen. Hal ini terlihat karena pada dua metode yang digunakan (Jacobi dan Gauss-Seidel), tidak mendapat solusi apapun karena iterasiyang dilakukan sangat banyak sehingga menyebabkan overflow. Untuk menemukan solusi SPL tsb mungkin bisa digunakan metode lain seperti SOR yang mungkin lebih efektif untuk mempercepat proses komputasi.